### ISSUE TITLE
Regression in fast-glob@3.2.0

### ISSUE THREAD

**Issue by anilanar** [sindresorhus/globby#142]
Just a friendly notification that due to a regression in `fast-glob@3.2.0`, `globby` broke too: https://github.com/mrmlnc/fast-glob/issues/253

Downstream example: https://github.com/dotansimha/graphql-code-generator/issues/3512

**Comment by therealpecus** [comment]
fast-glob updated to 3.2.2 but there is still a regression uncaught. I don't have much data, we tracked it in an upstream project: https://github.com/dennisreimann/uiengine/issues/56

**Comment by mrmlnc** [comment]
The problem has been fixed in `fast-glob@3.2.1`. You can reinstall your dependencies, or update the `package-lock` file or something for yarn env.

**Comment by therealpecus** [comment]
@mrmlnc this might be a bit more elusive. globby might be missing a test to cover cases that arise in upstream packages because with either `fast-glob@3.2.1` or `fast-glob@3.2.2` the problem persists. 

Running globby test suite does not surface any issue with any of the fast-glob versions that break upstream and for which force-installing `fast-glob@3.1.1` fixes the behaviour instead.

**Comment by sindresorhus** [comment]
This issue was resolved in fast-glob@3.2.1 and globby now uses fast-glob@3.3.3. I've tested the patterns that previously caused issues and they all work correctly. Closing as resolved.
